// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1zudp77ddhAhPTdDE5BjLAJ7C7eLADGo',
    appId: '1:306597173605:web:c286327b339a9a071f698c',
    messagingSenderId: '306597173605',
    projectId: 'vosttroapp',
    authDomain: 'vosttroapp.firebaseapp.com',
    storageBucket: 'vosttroapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaCfhNVg6RVuSg7aP4W6hKsO6tgJBd4D8',
    appId: '1:306597173605:android:e85487a3a761e1581f698c',
    messagingSenderId: '306597173605',
    projectId: 'vosttroapp',
    storageBucket: 'vosttroapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsQpDwdNUWwT0ahFzShCYYmOlKnli_VVE',
    appId: '1:306597173605:ios:8854cb485fa87bec1f698c',
    messagingSenderId: '306597173605',
    projectId: 'vosttroapp',
    storageBucket: 'vosttroapp.firebasestorage.app',
    iosBundleId: 'com.example.vosttroAssetTracker',
  );
}
